# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jsonpath}
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriele Renzi"]
  s.date = %q{2010-01-25}
  s.description = %q{The gem implements a simple parser+evaluator for JSONPath expressions in Ruby. It is a fork of bruce-jsonpath which only adds support for underscore in fields and works with warnings enabled.}
  s.email = %q{rff.rff@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "jsonpath.gemspec",
     "lib/jsonpath.rb",
     "lib/jsonpath/nodes.rb",
     "lib/jsonpath/parser.rb",
     "lib/jsonpath/parser.treetop",
     "test/parser_test.rb",
     "test/reference_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/riffraff/jsonpath}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{JSONPath support for Ruby}
  s.test_files = [
    "test/parser_test.rb",
     "test/reference_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
  end
end

